services:
  database:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_URL: ${POSTGRES_DOCKER_URL}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
  application:
    build:
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_URL: ${POSTGRES_DOCKER_URL}
    ports:
      - "8080:8080"
    depends_on:
      - database